alias be='bundle exec'
alias d='du -d1 -h'
alias git='hub'
alias gv='vim $(g | ff 2 | fzf)'
alias h='history'
alias ls='ls --color=auto'
alias mkdir='mkdir -p'
alias rm='rm -i'
alias tmux='tmux -2'
alias v='g vi'
alias vi='vim'
alias vim='vim -O'
