alias cat="bat --theme=\"$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo Nord || echo 'Solarized (light)')\""
alias d='du -d1 -h'
alias git='hub'
alias k='kubectl'
alias kcd='k config use-context'
alias ls='ls --color=auto'
alias mkdir='mkdir -p'
alias rm='rm -i'
alias tmux='tmux -2'
alias v='g vi'
alias vi='vim'
alias vim='vim -O'
